import { test, expect } from "vitest";
import * as PS from "./useParseState";

test("should give review/report", async () => {
  const state = PS.parseState(
    {
      id: 4007,
      objectErrorList: [],
      project: "star",
      userId: 200000150,
      schoolCode: "hke",
      acayear: "2022/23",
      packageId: 15,
      source: 0,
      title: "2022-10-06",
      content: "",
      description: "",
      closeUrl: "",
      leaderboardCode: "",
      leaderboardMode: "",
      reportMode: "last",
      startTime: "2022-10-06 14:44:00",
      endTime: "2022-10-23 00:00:00",
      publishDate: "2022-10-06 14:44:24",
      published: 1,
      bcVer: "bc_2017",
      attempted: 1,
      ended: 1,
      timeAllowed: 0,
      timeBonus: 0,
      maxTrialNo: 1,
      maxTrialScore: 0,
      autoSaveInterval: 60,
      submitOnce: 1,
      cannotGoPrev: 0,
      forceAnswer: 0,
      showFeedback: 0,
      viewAfterSubmit: 0,
      preserveLastSubmitAns: 1,
      suppressMedia: 0,
      trialsAssigned: 0,
      trialsSubmitted: 0,
      trialsMarked: 0,
      trialsTotal: 0,
      sections: [
        {
          id: 3819,
          createAt: "2022-10-06 14:44:24",
          createBy: "hke-felixwong-tr",
          modifyAt: "2022-10-06 14:44:24",
          modifyBy: "hke-felixwong-tr",
          objectErrorList: [],
          paperId: 4007,
          seq: 1,
          title: "",
          content: "",
          noOfQuestions: 2,
          suggestedTime: 360,
          mode: "sequential",
          criteria: "",
          setting: '{"qtiplayer":{"type":"qtiplayer","score":1}}',
          sectionQuestions: [],
        },
      ],
      trials: [
        {
          paperId: 4007,
          userId: 200000151,
          schoolCode: "",
          submitted: 1,
          marked: 1,
          timeElapsed: 11,
          submitTime: "2022-10-06 15:09:15",
          forceSubmit: 0,
          score: 2,
          scoreBasic: 0,
          token:
            "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NjUwNDAxMjEsImV4cCI6MTY2NTA1MDkyMSwidXNlciI6eyJjaXR5X2lkIjoiaGtlLWZlbGl4d29uZy1zdCIsImdyYWRlX2xldmVsIjoiUzEiLCJzY2hvb2xfY2xhc3MiOiJTMUEiLCJjbGFzc19ubyI6bnVsbCwibmlja25hbWUiOiJXb25nIFl1ayBXaW5nLCBGZWxpeCIsImVtYWlsX2FkZHJlc3MiOiIiLCJzdGF0dXMiOjEsInNjaF9sZXZlbF9pZCI6MTAsInVzZXJfaWQiOjIwMDAwMDE1MSwicm9sZXMiOiIxMDAwMDAwMDYiLCJncm91cHMiOiI1ODZiMjY1NGMyODdkOF84MjMxNDg1NCw1ODZiMjY1NjExYTIzNF82MTI1MTY0Niw1ODZiMjY1Njk0ZmM0Nl8wNTUyNTU4NCw1ODcyZTlmMjJmZWM3MV83OTU2MTU5Myw1OTI2NWVkZDE5MzllNF80NzIwODk5MCw1ZDI1ODZjYWM5ZWZkNF84ODAwMjUzNCw1ZDI1OGM5ZGVlOTI3MV85NjAzNTU5Miw1ZDI1YWQ4MmVmNGIyM182ODMzOTA4MCw1YzkwYjhkYTRmODk2Ml85OTU3Njk0NCIsImNmdWxsbmFtZSI6IldvbmcgWXVrIFdpbmcsIEZlbGl4IiwiZWZ1bGxuYW1lIjoiV29uZyBZdWsgV2luZywgRmVsaXgiLCJzY2hvb2xjb2RlIjoiaGtlIiwic2NoX2NsYXNzIjoiQSJ9fQ.Cw_kyxpblycMsqr3iPLBsW6AXmjsUbRj1gUm7TPBihs",
          resourceLinkPk: 0,
          ltiUserId: "",
          state: "",
          id: 5341,
        },
      ],
      ownerModifyAt: "2022-10-06 14:44:24",
      ownerInfo: {
        cityId: "hke-felixwong-tr",
        schoolCode: "hke",
        gradeLevel: null,
        schoolClass: null,
        class: null,
        classNo: null,
        fullnameC: "Wong Yuk Wing, Felix",
        fullnameE: "Wong Yuk Wing, Felix",
        nickname: "Wong Yuk Wing, Felix",
        emailAddress: "",
        status: 1,
        schLevelId: 0,
        userId: 200000150,
        roles: ["100000005"],
      },
      school: {
        nameE: "HONG KONG EDUCATION CITY SCHOOL",
        nameC: "香港教育城學校",
        schType: "SEC",
        schoolCode: "hke",
      },
      bcaCode: "",
      mySubmmitedTrialNo: 1,
      status: {
        submission: "submitted",
        isFrozen: true,
        canStart: false,
        canView: false,
        canModify: false,
        canDelete: false,
        canAssign: false,
        canReview: true,
        canReport: true,
        reportSharedNum: 0,
        reportSharedAccepted: false,
      },
      tab: "",
    },
    "student"
  );
  expect(state).toEqual("studentReportReady");
});
