<template>
  <StarPage>
    <section class="">
      <StarBanner :subject="route.query['subject']" />
      <div class="max-w-[1680px] px-5 m-auto">
        <StarBreadcrumbNav :model="[{ label: 'My Papers' }, { label: '中文' }]" />
        <TabOption />
        <PDivider />
        <div class="flex justify-between h-12">
          <div class="flex space-x-2">
            <StarButton label="New" icon="material-symbols:add-rounded" variant="ghost" />

            <div class="card justify-content-center flex flex-wrap gap-3">
              <span class="p-input-icon-left">
                <Icon
                  icon="mynaui:search"
                  width="24px"
                  color="currentColor"
                  class="top-1/2 left-3 [&_*]:text-text-300 absolute m-0 -translate-y-1/2"
                />
                <PInputText v-model="value1" placeholder="Search" class="h-full border-none" />
              </span>
            </div>
          </div>
          <div class="flex justify-end space-x-1">
            <StarFilterMultipleSelect
              class="border-none"
              :options="[
                {
                  items: [
                    { label: 'All years', value: 'all', default: true },
                    { label: '2023/24', value: '2023/24' },
                    { label: '2022/23', value: '2022/23' },
                    { label: '2021/22', value: '2021/22' },
                    { label: '2020/21', value: '2020/21' },
                    { label: '2019/20', value: '2019/20' },
                  ],
                },
              ]"
            />
            <StarFilterMultipleSelect
              class="border-none"
              :options="[
                {
                  items: [
                    { label: 'All statuses', value: 'all', default: true },
                    { label: 'Pending', value: 'pending' },
                    { label: 'Ready', value: 'ready' },
                    { label: 'Not attempted', value: 'notAttempted' },
                    { label: 'Attempted', value: 'attempted' },
                    { label: 'Finished', value: 'finished' },
                  ],
                },
              ]"
            />
            <StarFilterMultipleSelect
              class="border-none"
              :options="[
                {
                  items: [
                    { label: 'All owners', value: 'all', default: true },
                    { label: 'You', value: 'you' },
                    { label: 'Others', value: 'other' },
                  ],
                },
              ]"
            />
            <StarFilterMultipleSelect
              class="border-none"
              placeholder="Sort by"
              :options="[
                {
                  label: 'Sort by',
                  ariaLabel: 'Sort by',
                  items: [
                    { label: 'Marking', value: 'marking' },
                    { label: 'Title', value: 'title' },
                    { label: 'Date started', value: 'dateStarted' },
                    { label: 'Date ended', value: 'dateEnded' },
                    { label: 'Status', value: 'status' },
                    { label: 'Owner', value: 'owner' },
                    { label: 'Date updated', value: 'dateUpdated' },
                  ],
                },
                {
                  separator: true,
                },
                {
                  label: 'Order',
                  ariaLabel: 'Order',
                  items: [
                    { label: 'Older first', value: 'olderFirst' },
                    { label: 'Newest first', value: 'newestFirst' },
                    { label: 'Z-A', value: 'z-a' },
                    { label: 'A-Z', value: 'a-z' },
                  ],
                },
              ]"
            />
          </div>
        </div>
        <div class="relative">
          <div>
            <StarBreadcrumbNav :model="[{ label: '未完成' }]" />
            <section class="grid gap-8 grid-cols-[repeat(auto-fill,minmax(320px,1fr))]">
              <StarCardPaperCard :role="item.role" :paper="item.paper" v-for="item in papers" />
              <!-- <StarCardPaperCard role="teacher" paper="" />
              <StarCardPaperCard role="teacher" paper="" />
              <StarCardPaperCard role="teacher" paper="" />
              <StarCardPaperCard role="teacher" paper="" /> -->
            </section>
          </div>
          <div>
            <StarBreadcrumbNav :model="[{ label: '已完成' }]" />
            <section class="grid gap-8 grid-cols-[repeat(auto-fill,minmax(320px,1fr))]">
              <!-- <StarCardPaperCard ownerName="John Doe" status="ready" />
              <StarCardPaperCard ownerName="John Doe" status="ready" /> -->
            </section>
          </div>
          <StarButton
            :label="$t('ui.showMore')"
            variant="ghost"
            class="min-w-[256px] absolute left-2/4 mt-8 mb-4 -translate-x-1/2"
          />
        </div>
        <div>{{ user }}</div>
        <StarFooter />
      </div>
    </section>
  </StarPage>
</template>
<script setup lang="ts">
import { useToast } from "primevue/usetoast";
import {
  StarFooter,
  StarPage,
  StarBanner,
  StarBreadcrumbNav,
  StarDivider,
  StarFilterMultipleSelect,
  StarCardPaperCard,
} from "#components";
import { TabOption } from "@/components/star/atom/Option";
import { Icon } from "@/components/star";
import { ref, watchEffect } from "vue";
import { useRoute } from "vue-router";
// import { useI18n } from "vue-i18n";
import { createBEM } from "@/composables";
import { camelCase } from "change-case/keys";
import { useQuery } from "vue-query";
import { useJwtQuery, useLoadMetaQuery, useLoadTeacherPaperQuery, useUser } from "@/services";

// const { t, locale } = useI18n();
const bem = createBEM("my-papers");
const route = useRoute();

const fetchSomething = () =>
  fetch("https://e.star.dev.hkedcity.net/jwt.php", {
    credentials: "include",
  })
    .then((r) => r.text())
    .then((r) => {
      console.log(`🚀 // DEBUG 🍔 ~ file: index.vue:25 ~ .then ~ r:`, r);
      return r;
    });
const value1 = ref(null);

// const { data, isLoading, isError, error, isFetching } = useQuery(["jwt"], fetchSomething);
const { data, isLoading, isError, error, isFetching } = useJwtQuery();
console.log(`🚀 // DEBUG 🍔 ~ file: index.vue:169 ~ data:`, data.value);
const { data: jwt } = useJwtQuery({ select: (_) => _.token });
const meta = useLoadMetaQuery();
console.log(`🚀 // DEBUG 🍔 ~ file: index.vue:174 ~ meta:`, meta.data.value);
const { data: teacherPaper } = useLoadTeacherPaperQuery();
const { data: user } = useUser();

// const papers = [

//   {
//     role: "teacher",
//     paper: camelCase(
//       {
//         id: 4189,
//         object_error_list: [],
//         project: "star",
//         user_id: 200000150,
//         school_code: "",
//         acayear: "",
//         package_id: 13,
//         source: 0,
//         title: "Copy of student preset paper",
//         content: "",
//         description: "",
//         close_url: "",
//         leaderboard_code: "",
//         leaderboard_mode: "",
//         report_mode: "last",
//         start_time: "2023-10-05 00:00:00",
//         end_time: "2099-12-31 00:00:00",
//         publish_date: "",
//         published: 0,
//         bc_ver: "bc_2000",
//         attempted: 0,
//         ended: 0,
//         time_allowed: 0,
//         time_bonus: 0,
//         max_trial_no: 0,
//         max_trial_score: 0,
//         auto_save_interval: 60,
//         submit_once: 1,
//         cannot_go_prev: 0,
//         force_answer: 0,
//         show_feedback: 0,
//         view_after_submit: 1,
//         preserve_last_submit_ans: 1,
//         suppress_media: 0,
//         trials_assigned: 0,
//         trials_submitted: 0,
//         trials_marked: 0,
//         trials_total: 0,
//         sections: [
//           {
//             id: 4001,
//             create_at: "2023-10-13 11:29:17",
//             create_by: "hke-felixwong-tr",
//             modify_at: "2023-10-13 11:29:17",
//             modify_by: "hke-felixwong-tr",
//             object_error_list: [],
//             paper_id: 4189,
//             seq: 1,
//             title: "",
//             content: "",
//             no_of_questions: 1,
//             suggested_time: 1200,
//             mode: "sequential",
//             criteria: "",
//             setting: '{"qtiplayer":{"type":"qtiplayer","score":1}}',
//             section_questions: [],
//           },
//         ],
//         trials: [],
//         owner_modify_at: "2023-10-13 11:29:17",
//         owner_info: {
//           city_id: "hke-felixwong-tr",
//           school_code: "hke",
//           grade_level: null,
//           school_class: null,
//           class: null,
//           class_no: null,
//           fullname_c: "Wong Yuk Wing, Felix",
//           fullname_e: "Wong Yuk Wing, Felix",
//           nickname: "Wong Yuk Wing, Felix",
//           email_address: "",
//           status: 1,
//           sch_level_id: 0,
//           user_id: 200000150,
//           roles: ["100000005"],
//         },
//         feedback_status: "none",
//         bca_code: "",
//         acl: [
//           {
//             id: 9483,
//             create_at: "2023-10-13 11:29:17",
//             create_by: "hke-felixwong-tr",
//             modify_at: "2023-10-13 11:29:17",
//             modify_by: "hke-felixwong-tr",
//             object_error_list: [],
//             project: "star",
//             entity_type: "paper",
//             entity_id: 4189,
//             function_type: "attempt",
//             rule_set: "user",
//             rule_type: "group",
//             rule_value_1: "65017d6e2c6875_26275603",
//             rule_value_2: "",
//             rule_value_3: "",
//             rule_value_4: "",
//             status: "enabled",
//             remarks: "",
//           },
//           {
//             id: 9481,
//             create_at: "2023-10-13 11:29:17",
//             create_by: "hke-felixwong-tr",
//             modify_at: "2023-10-13 11:29:17",
//             modify_by: "hke-felixwong-tr",
//             object_error_list: [],
//             project: "star",
//             entity_type: "paper",
//             entity_id: 4189,
//             function_type: "attempt",
//             rule_set: "user",
//             rule_type: "school_level_class",
//             rule_value_1: "hke-11-A",
//             rule_value_2: "",
//             rule_value_3: "",
//             rule_value_4: "",
//             status: "enabled",
//             remarks: "",
//           },
//         ],
//         status: {
//           is_frozen: false,
//           can_start: false,
//           can_preview: true,
//           can_view: true,
//           can_modify: true,
//           can_delete: true,
//           can_assign: true,
//           can_review: false,
//           can_report: false,
//           report_shared_num: 0,
//           report_shared_accepted: false,
//           can_publish: false,
//           can_recall: false,
//           can_share_paper: true,
//           can_share_report: false,
//           can_accept: false,
//           can_reject: false,
//           compiled_by: "myself",
//           submission: "not_attempted",
//         },
//         tab: "",
//       },
//       Number.MAX_SAFE_INTEGER
//     ),
//   },
//   {
//     role: "teacher",
//     paper: camelCase(
//       {
//         id: 1819,
//         object_error_list: [],
//         project: "star",
//         user_id: 200000045,
//         school_code: "prj",
//         acayear: "",
//         package_id: 13,
//         source: 0,
//         title: "#05 teacher preset paper",
//         content: "",
//         description: "",
//         close_url: "",
//         leaderboard_code: "",
//         leaderboard_mode: "",
//         report_mode: "last",
//         start_time: "",
//         end_time: "",
//         publish_date: "",
//         published: 1,
//         bc_ver: "",
//         attempted: 0,
//         ended: 0,
//         time_allowed: 0,
//         time_bonus: 0,
//         max_trial_no: 1,
//         max_trial_score: 0,
//         auto_save_interval: 60,
//         submit_once: 1,
//         cannot_go_prev: 0,
//         force_answer: 0,
//         show_feedback: 0,
//         view_after_submit: 0,
//         preserve_last_submit_ans: 1,
//         suppress_media: 0,
//         trials_assigned: 0,
//         trials_submitted: 0,
//         trials_marked: 0,
//         trials_total: 0,
//         sections: [
//           {
//             id: 1475,
//             create_at: "2017-02-20 17:06:23",
//             create_by: "hke-system",
//             modify_at: "2017-02-20 17:06:23",
//             modify_by: "hke-system",
//             object_error_list: [],
//             paper_id: 1819,
//             seq: 1,
//             title: "",
//             content: "",
//             no_of_questions: 4,
//             suggested_time: 3240,
//             mode: "sequential",
//             criteria: "",
//             setting: '{"qtiplayer":{"type":"qtiplayer","score":1}}',
//             section_questions: [],
//           },
//         ],
//         trials: [],
//         owner_modify_at: "2017-02-20 17:06:23",
//         owner_info: {
//           city_id: "prj-star_tr1",
//           school_code: "prj",
//           grade_level: null,
//           school_class: null,
//           class: null,
//           class_no: null,
//           fullname_c: "預設評估",
//           fullname_e: "Preset Papers",
//           nickname: null,
//           email_address: "",
//           status: 1,
//           sch_level_id: 0,
//           user_id: 200000045,
//           roles: ["100000005"],
//         },
//         school: {
//           name_e: "PROJECT TESTING, HKEDCITY",
//           name_c: "教城專案測試學校",
//           sch_type: "SEC",
//           school_code: "prj",
//         },
//         feedback_status: "none",
//         bca_code: "",
//         acl: [],
//         status: {
//           is_frozen: true,
//           can_start: false,
//           can_preview: true,
//           can_view: true,
//           can_modify: false,
//           can_delete: false,
//           can_assign: false,
//           can_review: false,
//           can_report: false,
//           report_shared_num: 0,
//           report_shared_accepted: false,
//           can_publish: false,
//           can_recall: false,
//           can_share_paper: false,
//           can_share_report: false,
//           can_accept: true,
//           can_reject: true,
//           compiled_by: "others",
//           submission: "ready",
//         },
//         tab: "teacher_preset",
//         type: "teacher_preset",
//       },
//       Number.MAX_SAFE_INTEGER
//     ),
//   },
//   {
//     role: "teacher",
//     paper: camelCase(
//       {
//         id: 3470,
//         object_error_list: [],
//         project: "star",
//         user_id: 100001371,
//         school_code: "hke",
//         acayear: "2021/22",
//         package_id: 13,
//         source: 0,
//         title: "Super Task HKECL_TEST_AC1",
//         content: "",
//         description: "",
//         close_url: "",
//         leaderboard_code: "",
//         leaderboard_mode: "",
//         report_mode: "last",
//         start_time: "2021-10-08 10:44:00",
//         end_time: "2022-08-28 18:15:00",
//         publish_date: "2021-10-08 10:44:23",
//         published: 1,
//         bc_ver: "bc_2000",
//         attempted: 1,
//         ended: 1,
//         time_allowed: 0,
//         time_bonus: 0,
//         max_trial_no: 0,
//         max_trial_score: 0,
//         auto_save_interval: 60,
//         submit_once: 1,
//         cannot_go_prev: 0,
//         force_answer: 0,
//         show_feedback: 0,
//         view_after_submit: 1,
//         preserve_last_submit_ans: 1,
//         suppress_media: 0,
//         trials_assigned: 0,
//         trials_submitted: 0,
//         trials_marked: 0,
//         trials_total: 0,
//         sections: [
//           {
//             id: 3120,
//             create_at: "2021-10-08 10:40:17",
//             create_by: "hke-adrian-tr",
//             modify_at: "2021-10-08 10:52:14",
//             modify_by: "hke-adrian-tr",
//             object_error_list: [],
//             paper_id: 3470,
//             seq: 1,
//             title: "",
//             content: "",
//             no_of_questions: 1,
//             suggested_time: 3600,
//             mode: "sequential",
//             criteria: "",
//             setting: '{"qtiplayer":{"type":"qtiplayer","score":1}}',
//             section_questions: [],
//           },
//         ],
//         trials: [],
//         owner_modify_at: "2021-10-08 10:52:13",
//         owner_info: {
//           city_id: "hke-adrian-tr",
//           school_code: "hke",
//           grade_level: null,
//           school_class: null,
//           class: null,
//           class_no: null,
//           fullname_c: "水埗鰂魚7",
//           fullname_e: "English Man6",
//           nickname: "水埗鰂魚涌ha",
//           email_address: "",
//           status: 1,
//           sch_level_id: 0,
//           user_id: 100001371,
//           roles: ["100000005"],
//         },
//         school: {
//           name_e: "HONG KONG EDUCATION CITY SCHOOL",
//           name_c: "香港教育城學校",
//           sch_type: "SEC",
//           school_code: "hke",
//         },
//         feedback_status: "pending",
//         bca_code: "",
//         acl: [
//           {
//             id: 6870,
//             create_at: "2021-10-08 10:44:24",
//             create_by: "hke-adrian-tr",
//             modify_at: "2021-10-08 10:52:14",
//             modify_by: "hke-adrian-tr",
//             object_error_list: [],
//             project: "star",
//             entity_type: "paper",
//             entity_id: 3470,
//             function_type: "attempt",
//             rule_set: "user",
//             rule_type: "group",
//             rule_value_1: "5872e9f22fec71_79561593",
//             rule_value_2: "",
//             rule_value_3: "",
//             rule_value_4: "",
//             status: "enabled",
//             remarks: "",
//           },
//         ],
//         status: {
//           is_frozen: true,
//           can_start: false,
//           can_preview: true,
//           can_view: true,
//           can_modify: false,
//           can_delete: false,
//           can_assign: false,
//           can_review: false,
//           can_report: false,
//           report_shared_num: 0,
//           report_shared_accepted: false,
//           can_publish: false,
//           can_recall: false,
//           can_share_paper: true,
//           can_share_report: false,
//           can_accept: true,
//           can_reject: true,
//           compiled_by: "others",
//           submission: "finished",
//         },
//         tab: "shared",
//       },
//       Number.MAX_SAFE_INTEGER
//     ),
//   },
//   {
//     role: "teacher",
//     paper: camelCase(
//       {
//         id: 3843,
//         object_error_list: [],
//         project: "star",
//         user_id: 0,
//         school_code: "",
//         acayear: "",
//         package_id: 13,
//         source: 100001371,
//         title: "Super Task HKECL_TEST_AC1",
//         content: "",
//         description: "",
//         close_url: "",
//         leaderboard_code: "",
//         leaderboard_mode: "",
//         report_mode: "last",
//         start_time: "",
//         end_time: "",
//         publish_date: "",
//         published: 1,
//         bc_ver: "bc_2000",
//         attempted: 0,
//         ended: 0,
//         time_allowed: 0,
//         time_bonus: 0,
//         max_trial_no: 0,
//         max_trial_score: 0,
//         auto_save_interval: 60,
//         submit_once: 1,
//         cannot_go_prev: 0,
//         force_answer: 0,
//         show_feedback: 0,
//         view_after_submit: 1,
//         preserve_last_submit_ans: 1,
//         suppress_media: 0,
//         trials_assigned: 0,
//         trials_submitted: 0,
//         trials_marked: 0,
//         trials_total: 0,
//         sections: [
//           {
//             id: 3655,
//             create_at: "2022-08-08 15:01:40",
//             create_by: "hke-adrian-tr",
//             modify_at: "2022-08-08 15:01:40",
//             modify_by: "hke-adrian-tr",
//             object_error_list: [],
//             paper_id: 3843,
//             seq: 1,
//             title: "",
//             content: "",
//             no_of_questions: 1,
//             suggested_time: 3600,
//             mode: "sequential",
//             criteria: "",
//             setting: '{"qtiplayer":{"type":"qtiplayer","score":1}}',
//             section_questions: [],
//           },
//         ],
//         trials: [],
//         owner_modify_at: "2021-10-08 10:52:13",
//         owner_info: {
//           city_id: "hke-adrian-tr",
//           school_code: "hke",
//           grade_level: null,
//           school_class: null,
//           class: null,
//           class_no: null,
//           fullname_c: "水埗鰂魚7",
//           fullname_e: "English Man6",
//           nickname: "水埗鰂魚涌ha",
//           email_address: "",
//           status: 1,
//           sch_level_id: 0,
//           user_id: 100001371,
//           roles: ["100000005"],
//         },
//         feedback_status: "required",
//         bca_code: "",
//         acl: [],
//         status: {
//           is_frozen: false,
//           can_start: false,
//           can_preview: true,
//           can_view: true,
//           can_modify: false,
//           can_delete: false,
//           can_assign: false,
//           can_review: false,
//           can_report: false,
//           report_shared_num: 0,
//           report_shared_accepted: false,
//           can_publish: false,
//           can_recall: false,
//           can_share_paper: true,
//           can_share_report: false,
//           can_accept: true,
//           can_reject: true,
//           compiled_by: "others",
//           submission: "not_attempted",
//         },
//         tab: "shared",
//       },
//       Number.MAX_SAFE_INTEGER
//     ),
//   },
//   {
//     role: "teacher",
//     paper: camelCase(
//       {
//         id: 2969,
//         object_error_list: [],
//         project: "star",
//         user_id: 200000057,
//         school_code: "hke",
//         acayear: "2020/21",
//         package_id: 13,
//         source: 200000057,
//         title: "6CR1 BCA2021 to ASE",
//         content: "",
//         description: "",
//         close_url: "",
//         leaderboard_code: "6CRS",
//         leaderboard_mode: "",
//         report_mode: "last",
//         start_time: "2021-04-29 00:00:00",
//         end_time: "2021-08-27 17:00:00",
//         publish_date: "2021-04-28 10:50:09",
//         published: 1,
//         bc_ver: "bc_2000",
//         attempted: 1,
//         ended: 1,
//         time_allowed: 0,
//         time_bonus: 0,
//         max_trial_no: 1,
//         max_trial_score: 0,
//         auto_save_interval: 60,
//         submit_once: 1,
//         cannot_go_prev: 0,
//         force_answer: 0,
//         show_feedback: 0,
//         view_after_submit: 0,
//         preserve_last_submit_ans: 1,
//         suppress_media: 0,
//         trials_assigned: 0,
//         trials_submitted: 0,
//         trials_marked: 0,
//         trials_total: 0,
//         sections: [
//           {
//             id: 2623,
//             create_at: "2020-12-10 11:05:08",
//             create_by: "hke-adrian-tr",
//             modify_at: "2021-04-28 10:50:10",
//             modify_by: "hke-adrian-tr",
//             object_error_list: [],
//             paper_id: 2969,
//             seq: 1,
//             title: "",
//             content: "",
//             no_of_questions: 3,
//             suggested_time: 1800,
//             mode: "sequential",
//             criteria: "",
//             setting: '{"qtiplayer":{"type":"qtiplayer","score":1}}',
//             section_questions: [],
//           },
//         ],
//         trials: [],
//         owner_modify_at: "2021-04-28 10:50:09",
//         owner_info: {
//           city_id: "prj-star_tr6",
//           school_code: "prj",
//           grade_level: null,
//           school_class: null,
//           class: null,
//           class_no: null,
//           fullname_c: "評估材料",
//           fullname_e: "Assessment resources",
//           nickname: "評估材料 Assessment resources (GU21)",
//           email_address: "",
//           status: 1,
//           sch_level_id: 0,
//           user_id: 200000057,
//           roles: ["100000005"],
//         },
//         school: {
//           name_e: "HONG KONG EDUCATION CITY SCHOOL",
//           name_c: "香港教育城學校",
//           sch_type: "SEC",
//           school_code: "hke",
//         },
//         feedback_status: "none",
//         bca_code: "bca2021",
//         is_bca: 1,
//         is_bca_mock: 0,
//         is_brief_report: true,
//         acl: [
//           {
//             id: 6179,
//             create_at: "2021-04-28 10:50:10",
//             create_by: "hke-adrian-tr",
//             modify_at: "2021-04-28 10:50:10",
//             modify_by: "hke-adrian-tr",
//             object_error_list: [],
//             project: "star",
//             entity_type: "paper",
//             entity_id: 2969,
//             function_type: "attempt",
//             rule_set: "user",
//             rule_type: "user_id",
//             rule_value_1: "100001373",
//             rule_value_2: "",
//             rule_value_3: "",
//             rule_value_4: "",
//             status: "enabled",
//             remarks: "",
//           },
//           {
//             id: 6173,
//             create_at: "2021-04-28 10:50:10",
//             create_by: "hke-adrian-tr",
//             modify_at: "2021-04-28 10:50:10",
//             modify_by: "hke-adrian-tr",
//             object_error_list: [],
//             project: "star",
//             entity_type: "paper",
//             entity_id: 2969,
//             function_type: "attempt",
//             rule_set: "user",
//             rule_type: "user_id",
//             rule_value_1: "100001411",
//             rule_value_2: "",
//             rule_value_3: "",
//             rule_value_4: "",
//             status: "enabled",
//             remarks: "",
//           },
//           {
//             id: 6175,
//             create_at: "2021-04-28 10:50:10",
//             create_by: "hke-adrian-tr",
//             modify_at: "2021-04-28 10:50:10",
//             modify_by: "hke-adrian-tr",
//             object_error_list: [],
//             project: "star",
//             entity_type: "paper",
//             entity_id: 2969,
//             function_type: "attempt",
//             rule_set: "user",
//             rule_type: "user_id",
//             rule_value_1: "100001762",
//             rule_value_2: "",
//             rule_value_3: "",
//             rule_value_4: "",
//             status: "enabled",
//             remarks: "",
//           },
//           {
//             id: 6171,
//             create_at: "2021-04-28 10:50:10",
//             create_by: "hke-adrian-tr",
//             modify_at: "2021-04-28 10:50:10",
//             modify_by: "hke-adrian-tr",
//             object_error_list: [],
//             project: "star",
//             entity_type: "paper",
//             entity_id: 2969,
//             function_type: "attempt",
//             rule_set: "user",
//             rule_type: "user_id",
//             rule_value_1: "200000016",
//             rule_value_2: "",
//             rule_value_3: "",
//             rule_value_4: "",
//             status: "enabled",
//             remarks: "",
//           },
//           {
//             id: 6169,
//             create_at: "2021-04-28 10:50:10",
//             create_by: "hke-adrian-tr",
//             modify_at: "2021-04-28 10:50:10",
//             modify_by: "hke-adrian-tr",
//             object_error_list: [],
//             project: "star",
//             entity_type: "paper",
//             entity_id: 2969,
//             function_type: "attempt",
//             rule_set: "user",
//             rule_type: "user_id",
//             rule_value_1: "200000022",
//             rule_value_2: "",
//             rule_value_3: "",
//             rule_value_4: "",
//             status: "enabled",
//             remarks: "",
//           },
//           {
//             id: 6177,
//             create_at: "2021-04-28 10:50:10",
//             create_by: "hke-adrian-tr",
//             modify_at: "2021-04-28 10:50:10",
//             modify_by: "hke-adrian-tr",
//             object_error_list: [],
//             project: "star",
//             entity_type: "paper",
//             entity_id: 2969,
//             function_type: "attempt",
//             rule_set: "user",
//             rule_type: "user_id",
//             rule_value_1: "45278405",
//             rule_value_2: "",
//             rule_value_3: "",
//             rule_value_4: "",
//             status: "enabled",
//             remarks: "",
//           },
//         ],
//         status: {
//           is_frozen: true,
//           can_start: false,
//           can_preview: true,
//           can_view: true,
//           can_modify: false,
//           can_delete: false,
//           can_assign: false,
//           can_review: false,
//           can_report: true,
//           report_shared_num: 0,
//           report_shared_accepted: true,
//           can_publish: false,
//           can_recall: false,
//           can_share_paper: true,
//           can_share_report: true,
//           can_accept: false,
//           can_reject: false,
//           compiled_by: "others",
//           submission: "finished",
//         },
//         tab: "bca2021",
//       },
//       Number.MAX_SAFE_INTEGER
//     ),
//   },
// ];
</script>
