import type { Meta, StoryObj } from "@storybook/vue3";
import { PaperCard } from "@/components/star/atom/Card";
import { camelCase } from "change-case/keys";

const meta: Meta<typeof PaperCard> = {
  title: "Components/PaperCard",
  tags: ["autodocs"],
  component: PaperCard,
};

export default meta;
type Story = StoryObj<typeof PaperCard>;

// const render: Story["render"] = (args, { argTypes }) => ({
//   components: { SelectItem },
//   setup() {
//     return { args };
//   },
//   template: '<SelectItem v-bind="args">{{ args.default }}</SelectItem>',
// });
export const Default: Story = {
  args: {
    paper: camelCase(
      {
        id: 4189,
        create_at: "2023-10-13 11:29:17",
        create_by: "hke-felixwong-tr",
        modify_at: "2023-10-13 11:29:17",
        modify_by: "hke-felixwong-tr",
        object_error_list: [],
        project: "star",
        user_id: 200000150,
        school_code: "",
        acayear: "",
        package_id: 13,
        source: 0,
        title: "Copy of student preset paper",
        content: "",
        description: "",
        close_url: "",
        leaderboard_code: "",
        leaderboard_mode: "",
        report_mode: "last",
        start_time: "2023-10-05 00:00:00",
        end_time: "2099-12-31 00:00:00",
        publish_date: "",
        published: 0,
        bc_ver: "bc_2000",
        attempted: 0,
        ended: 0,
        time_allowed: 0,
        time_bonus: 0,
        max_trial_no: 0,
        max_trial_score: 0,
        auto_save_interval: 60,
        submit_once: 1,
        cannot_go_prev: 0,
        force_answer: 0,
        show_feedback: 0,
        view_after_submit: 1,
        preserve_last_submit_ans: 1,
        suppress_media: 0,
        trials_assigned: 0,
        trials_submitted: 0,
        trials_marked: 0,
        trials_total: 0,
        sections: [
          {
            id: 4001,
            create_at: "2023-10-13 11:29:17",
            create_by: "hke-felixwong-tr",
            modify_at: "2023-10-13 11:29:17",
            modify_by: "hke-felixwong-tr",
            object_error_list: [],
            paper_id: 4189,
            seq: 1,
            title: "",
            content: "",
            no_of_questions: 1,
            suggested_time: 1200,
            mode: "sequential",
            criteria: "",
            setting: '{"qtiplayer":{"type":"qtiplayer","score":1}}',
            section_questions: [],
          },
        ],
        trials: [],
        owner_modify_at: "2023-10-13 11:29:17",
        owner_info: {
          city_id: "hke-felixwong-tr",
          school_code: "hke",
          grade_level: null,
          school_class: null,
          class: null,
          class_no: null,
          fullname_c: "Wong Yuk Wing, Felix",
          fullname_e: "Wong Yuk Wing, Felix",
          nickname: "Wong Yuk Wing, Felix",
          email_address: "",
          status: 1,
          sch_level_id: 0,
          user_id: 200000150,
          roles: ["100000005"],
        },
        feedback_status: "none",
        bca_code: "",
        my_submmited_trial_no: 0,
        acl: [
          {
            id: 9483,
            create_at: "2023-10-13 11:29:17",
            create_by: "hke-felixwong-tr",
            modify_at: "2023-10-13 11:29:17",
            modify_by: "hke-felixwong-tr",
            object_error_list: [],
            project: "star",
            entity_type: "paper",
            entity_id: 4189,
            function_type: "attempt",
            rule_set: "user",
            rule_type: "group",
            rule_value_1: "65017d6e2c6875_26275603",
            rule_value_2: "",
            rule_value_3: "",
            rule_value_4: "",
            status: "enabled",
            remarks: "",
          },
          {
            id: 9481,
            create_at: "2023-10-13 11:29:17",
            create_by: "hke-felixwong-tr",
            modify_at: "2023-10-13 11:29:17",
            modify_by: "hke-felixwong-tr",
            object_error_list: [],
            project: "star",
            entity_type: "paper",
            entity_id: 4189,
            function_type: "attempt",
            rule_set: "user",
            rule_type: "school_level_class",
            rule_value_1: "hke-11-A",
            rule_value_2: "",
            rule_value_3: "",
            rule_value_4: "",
            status: "enabled",
            remarks: "",
          },
        ],
        status: {
          is_frozen: false,
          can_start: false,
          can_preview: true,
          can_view: true,
          can_modify: true,
          can_delete: true,
          can_assign: true,
          can_review: false,
          can_report: false,
          report_shared_num: 0,
          report_shared_accepted: false,
        },
      },
      Number.MAX_SAFE_INTEGER
    ),
  },
};
export const SystemPaper: Story = {
  args: {
    paper: camelCase(
      {
        id: 714,
        create_at: "2017-02-16 15:13:55",
        create_by: "hke-system",
        modify_at: "2023-12-01 15:16:52",
        modify_by: "hke-system",
        object_error_list: [],
        project: "star",
        user_id: 100001369,
        school_code: "prj",
        acayear: "",
        package_id: 13,
        source: 0,
        title: "#14 student preset paper",
        content: "",
        description: "using Q in pk 13",
        close_url: "",
        leaderboard_code: "",
        leaderboard_mode: "",
        report_mode: "last",
        start_time: "2023-10-05 00:00:00",
        end_time: "2099-12-31 00:00:00",
        publish_date: "2023-10-05 00:00:00",
        published: 1,
        bc_ver: "",
        attempted: 1,
        ended: 0,
        time_allowed: 0,
        time_bonus: 0,
        max_trial_no: 0,
        max_trial_score: 0,
        auto_save_interval: 60,
        submit_once: 1,
        cannot_go_prev: 0,
        force_answer: 0,
        show_feedback: 0,
        view_after_submit: 1,
        preserve_last_submit_ans: 1,
        suppress_media: 0,
        trials_assigned: 1,
        trials_submitted: 0,
        trials_marked: 4,
        trials_total: 5,
        sections: [
          {
            id: 622,
            create_at: "2017-02-16 15:13:55",
            create_by: "hke-system",
            modify_at: "2023-10-05 10:15:16",
            modify_by: "hke-system",
            object_error_list: [],
            paper_id: 714,
            seq: 1,
            title: "",
            content: "",
            no_of_questions: 1,
            suggested_time: 680,
            mode: "sequential",
            criteria: "",
            setting: '{"qtiplayer":{"type":"qtiplayer","score":1}}',
            section_questions: [],
          },
        ],
        trials: [],
        owner_modify_at: "2017-02-16 15:13:55",
        owner_info: {
          city_id: "hke-adrian",
          school_code: null,
          grade_level: null,
          school_class: null,
          class: null,
          class_no: null,
          fullname_c: "水埗鰂魚",
          fullname_e: "English people",
          nickname: "水埗鰂魚",
          email_address: "",
          status: 1,
          sch_level_id: 0,
          user_id: 100001369,
          roles: ["100000004"],
        },
        school: {
          name_e: "PROJECT TESTING, HKEDCITY",
          name_c: "教城專案測試學校",
          sch_type: "SEC",
          school_code: "prj",
        },
        feedback_status: "none",
        bca_code: "",
        my_submmited_trial_no: 0,
        acl: [
          {
            id: 9403,
            create_at: "2017-02-16 15:13:56",
            create_by: "hke-system",
            modify_at: "2017-02-16 15:13:56",
            modify_by: "hke-system",
            object_error_list: [],
            project: "star",
            entity_type: "paper",
            entity_id: 714,
            function_type: "attempt",
            rule_set: "user",
            rule_type: "school_role",
            rule_value_1: "*-100000006",
            rule_value_2: "",
            rule_value_3: "",
            rule_value_4: "",
            status: "enabled",
            remarks: "",
          },
        ],
        status: {
          is_frozen: true,
          can_start: false,
          can_preview: true,
          can_view: true,
          can_modify: false,
          can_delete: false,
          can_assign: false,
          can_review: false,
          can_report: true,
          report_shared_num: 0,
          report_shared_accepted: true,
        },
      },
      Number.MAX_SAFE_INTEGER
    ),
  },
};
export const SystemPaperWithManualMarking: Story = {
  args: {
    paper: camelCase(
      {
        id: 4302,
        create_at: "2017-02-16 15:13:55",
        create_by: "hke-system",
        modify_at: "2023-12-01 15:17:03",
        modify_by: "hke-system",
        object_error_list: [],
        project: "star",
        user_id: 100001369,
        school_code: "prj",
        acayear: "",
        package_id: 13,
        source: 0,
        title: "#21 student preset paper",
        content: "",
        description: "using Q in pk 73",
        close_url: "",
        leaderboard_code: "",
        leaderboard_mode: "",
        report_mode: "last",
        start_time: "2023-12-01 00:00:00",
        end_time: "2099-12-31 00:00:00",
        publish_date: "2023-12-01 00:00:00",
        published: 1,
        bc_ver: "",
        attempted: 1,
        ended: 0,
        time_allowed: 0,
        time_bonus: 0,
        max_trial_no: 0,
        max_trial_score: 0,
        auto_save_interval: 60,
        submit_once: 1,
        cannot_go_prev: 0,
        force_answer: 0,
        show_feedback: 0,
        view_after_submit: 1,
        preserve_last_submit_ans: 1,
        suppress_media: 0,
        trials_assigned: 1,
        trials_submitted: 0,
        trials_marked: 0,
        trials_total: 1,
        sections: [
          {
            id: 4114,
            create_at: "2017-02-16 15:13:55",
            create_by: "hke-system",
            modify_at: "2023-10-05 10:15:16",
            modify_by: "hke-system",
            object_error_list: [],
            paper_id: 4302,
            seq: 1,
            title: "",
            content: "",
            no_of_questions: 1,
            suggested_time: 680,
            mode: "sequential",
            criteria: "",
            setting: '{"qtiplayer":{"type":"qtiplayer","score":1}}',
            section_questions: [],
          },
        ],
        trials: [],
        owner_modify_at: "2017-02-16 15:13:55",
        owner_info: {
          city_id: "hke-adrian",
          school_code: null,
          grade_level: null,
          school_class: null,
          class: null,
          class_no: null,
          fullname_c: "水埗鰂魚",
          fullname_e: "English people",
          nickname: "水埗鰂魚",
          email_address: "",
          status: 1,
          sch_level_id: 0,
          user_id: 100001369,
          roles: ["100000004"],
        },
        school: {
          name_e: "PROJECT TESTING, HKEDCITY",
          name_c: "教城專案測試學校",
          sch_type: "SEC",
          school_code: "prj",
        },
        feedback_status: "required",
        bca_code: "",
        my_submmited_trial_no: 0,
        acl: [
          {
            id: 9822,
            create_at: "2017-02-16 15:13:56",
            create_by: "hke-system",
            modify_at: "2017-02-16 15:13:56",
            modify_by: "hke-system",
            object_error_list: [],
            project: "star",
            entity_type: "paper",
            entity_id: 4302,
            function_type: "attempt",
            rule_set: "user",
            rule_type: "school_role",
            rule_value_1: "*-100000006",
            rule_value_2: "",
            rule_value_3: "",
            rule_value_4: "",
            status: "enabled",
            remarks: "",
          },
        ],
        status: {
          is_frozen: true,
          can_start: false,
          can_preview: true,
          can_view: true,
          can_modify: false,
          can_delete: false,
          can_assign: false,
          can_review: false,
          can_report: true,
          report_shared_num: 0,
          report_shared_accepted: true,
        },
      },
      Number.MAX_SAFE_INTEGER
    ),
  },
};
export const SharedPaperWithManualMarking: Story = {
  args: {
    paper: camelCase(
      {
        id: 4282,
        create_at: "2023-11-30 17:08:33",
        create_by: "hke-adrian-tr",
        modify_at: "2023-12-04 10:24:21",
        modify_by: "hke-adrian-tr",
        object_error_list: [],
        project: "star",
        user_id: 100001371,
        school_code: "hke",
        acayear: "2023/24",
        package_id: 13,
        source: 0,
        title: "3Q with everything to ANA",
        content: "",
        description: "",
        close_url: "",
        leaderboard_code: "",
        leaderboard_mode: "",
        report_mode: "last",
        start_time: "2023-11-30 17:08:00",
        end_time: "2024-08-30 19:15:00",
        publish_date: "2023-11-30 17:08:00",
        published: 1,
        bc_ver: "bc_2000",
        attempted: 1,
        ended: 0,
        time_allowed: 0,
        time_bonus: 0,
        max_trial_no: 0,
        max_trial_score: 0,
        auto_save_interval: 60,
        submit_once: 1,
        cannot_go_prev: 0,
        force_answer: 0,
        show_feedback: 0,
        view_after_submit: 1,
        preserve_last_submit_ans: 1,
        suppress_media: 0,
        trials_assigned: 2,
        trials_submitted: 0,
        trials_marked: 1,
        trials_total: 3,
        sections: [
          {
            id: 4094,
            create_at: "2023-11-30 17:08:33",
            create_by: "hke-adrian-tr",
            modify_at: "2023-11-30 17:08:33",
            modify_by: "hke-adrian-tr",
            object_error_list: [],
            paper_id: 4282,
            seq: 1,
            title: "",
            content: "",
            no_of_questions: 3,
            suggested_time: 4080,
            mode: "sequential",
            criteria: "",
            setting: '{"qtiplayer":{"type":"qtiplayer","score":1}}',
            section_questions: [],
          },
        ],
        trials: [],
        owner_modify_at: "2023-11-30 17:08:33",
        owner_info: {
          city_id: "hke-adrian-tr",
          school_code: "hke",
          grade_level: null,
          school_class: null,
          class: null,
          class_no: null,
          fullname_c: "水埗鰂魚7",
          fullname_e: "English Man6",
          nickname: "水埗鰂魚涌ha",
          email_address: "",
          status: 1,
          sch_level_id: 0,
          user_id: 100001371,
          roles: ["100000005"],
        },
        school: {
          name_e: "HONG KONG EDUCATION CITY SCHOOL",
          name_c: "香港教育城學校",
          sch_type: "SEC",
          school_code: "hke",
        },
        feedback_status: "pending",
        bca_code: "",
        my_submmited_trial_no: 0,
        acl: [
          {
            id: 9728,
            create_at: "2023-11-30 17:08:33",
            create_by: "hke-adrian-tr",
            modify_at: "2023-11-30 17:08:33",
            modify_by: "hke-adrian-tr",
            object_error_list: [],
            project: "star",
            entity_type: "paper",
            entity_id: 4282,
            function_type: "attempt",
            rule_set: "user",
            rule_type: "group",
            rule_value_1: "5872e9f22fec71_79561593",
            rule_value_2: "",
            rule_value_3: "",
            rule_value_4: "",
            status: "enabled",
            remarks: "",
          },
        ],
        status: {
          is_frozen: false,
          can_start: false,
          can_preview: true,
          can_view: true,
          can_modify: false,
          can_delete: false,
          can_assign: false,
          can_review: false,
          can_report: false,
          report_shared_num: 0,
          report_shared_accepted: false,
        },
      },
      Number.MAX_SAFE_INTEGER
    ),
  },
};
export const StarNetworkSchoolProgramme: Story = {
  args: {
    paper: camelCase(
      {
        id: 2295,
        create_at: "2020-10-21 16:11:46",
        create_by: "hke-system",
        modify_at: "2020-10-21 16:11:46",
        modify_by: "hke-system",
        object_error_list: [],
        project: "star",
        user_id: 200000002,
        school_code: "prj",
        acayear: "",
        package_id: 13,
        source: 200000002,
        title: "NSP preset paper 中文科",
        content: "",
        description: "This is a NSP paper",
        close_url: "",
        leaderboard_code: "",
        leaderboard_mode: "",
        report_mode: "last",
        start_time: "2020-10-20 00:00:00",
        end_time: "2020-11-30 23:59:00",
        publish_date: "",
        published: 1,
        bc_ver: "bc_2000",
        attempted: 0,
        ended: 1,
        time_allowed: 0,
        time_bonus: 0,
        max_trial_no: 1,
        max_trial_score: 0,
        auto_save_interval: 60,
        submit_once: 1,
        cannot_go_prev: 0,
        force_answer: 0,
        show_feedback: 0,
        view_after_submit: 0,
        preserve_last_submit_ans: 1,
        suppress_media: 0,
        trials_assigned: 0,
        trials_submitted: 0,
        trials_marked: 0,
        trials_total: 0,
        sections: [
          {
            id: 1949,
            create_at: "2020-05-08 16:53:27",
            create_by: "za6-tea010",
            modify_at: "2020-05-08 16:53:27",
            modify_by: "za6-tea010",
            object_error_list: [],
            paper_id: 2295,
            seq: 1,
            title: "",
            content: "",
            no_of_questions: 3,
            suggested_time: 1800,
            mode: "sequential",
            criteria: "",
            setting: '{"qtiplayer":{"type":"qtiplayer","score":1}}',
            section_questions: [],
          },
        ],
        trials: [],
        owner_modify_at: "2020-10-21 16:11:46",
        owner_info: {
          city_id: "prj-star_tr5",
          school_code: "prj",
          grade_level: null,
          school_class: null,
          class: null,
          class_no: null,
          fullname_c: "網絡學校計劃",
          fullname_e: "Network School Programme",
          nickname: null,
          email_address: "",
          status: 1,
          sch_level_id: 0,
          user_id: 200000002,
          roles: ["100000005"],
        },
        school: {
          name_e: "PROJECT TESTING, HKEDCITY",
          name_c: "教城專案測試學校",
          sch_type: "SEC",
          school_code: "prj",
        },
        feedback_status: "none",
        bca_code: "nsp2020",
        is_bca: 1,
        is_bca_mock: 0,
        is_brief_report: false,
        my_submmited_trial_no: 0,
        acl: [],
        status: {
          is_frozen: true,
          can_start: false,
          can_preview: true,
          can_view: true,
          can_modify: false,
          can_delete: false,
          can_assign: false,
          can_review: false,
          can_report: false,
          report_shared_num: 0,
          report_shared_accepted: false,
        },
      },
      Number.MAX_SAFE_INTEGER
    ),
  },
};
export const AssessmentMaterials2022: Story = {
  args: {
    paper: camelCase(
      {
        id: 3689,
        create_at: "2022-04-22 09:46:21",
        create_by: "hke-system",
        modify_at: "2023-12-01 12:14:57",
        modify_by: "hke-system",
        object_error_list: [],
        project: "star",
        user_id: 200000128,
        school_code: "hke",
        acayear: "2021/22",
        package_id: 13,
        source: 200000128,
        title: "#11 bca2022 (system publish)",
        content: "",
        description: "",
        close_url: "",
        leaderboard_code: "3CRS-PD",
        leaderboard_mode: "",
        report_mode: "last",
        start_time: "2022-04-22 09:00:00",
        end_time: "2022-04-28 14:00:00",
        publish_date: "2022-04-22 09:46:21",
        published: 1,
        bc_ver: "bc_2000",
        attempted: 1,
        ended: 1,
        time_allowed: 0,
        time_bonus: 0,
        max_trial_no: 1,
        max_trial_score: 0,
        auto_save_interval: 60,
        submit_once: 1,
        cannot_go_prev: 0,
        force_answer: 0,
        show_feedback: 0,
        view_after_submit: 0,
        preserve_last_submit_ans: 1,
        suppress_media: 0,
        trials_assigned: 0,
        trials_submitted: 0,
        trials_marked: 3,
        trials_total: 3,
        sections: [
          {
            id: 3501,
            create_at: "2022-04-22 09:46:21",
            create_by: "hke-system",
            modify_at: "2022-04-22 09:46:21",
            modify_by: "hke-system",
            object_error_list: [],
            paper_id: 3689,
            seq: 1,
            title: "",
            content: "",
            no_of_questions: 2,
            suggested_time: 1500,
            mode: "sequential",
            criteria: "",
            setting: '{"qtiplayer":{"type":"qtiplayer","score":1}}',
            section_questions: [],
          },
        ],
        trials: [],
        owner_modify_at: "2022-04-22 09:46:21",
        owner_info: {
          city_id: "prj-star_tr7",
          school_code: "prj",
          grade_level: null,
          school_class: null,
          class: null,
          class_no: null,
          fullname_c: "評估材料",
          fullname_e: "Assessment resources",
          nickname: null,
          email_address: "",
          status: 1,
          sch_level_id: 0,
          user_id: 200000128,
          roles: ["100000005"],
        },
        school: {
          name_e: "HONG KONG EDUCATION CITY SCHOOL",
          name_c: "香港教育城學校",
          sch_type: "SEC",
          school_code: "hke",
        },
        feedback_status: "none",
        bca_code: "bca2022",
        is_bca: 1,
        is_bca_mock: 0,
        is_brief_report: true,
        my_submmited_trial_no: 0,
        acl: [
          {
            id: 7875,
            create_at: "2022-04-22 09:46:21",
            create_by: "hke-system",
            modify_at: "2022-04-22 09:46:21",
            modify_by: "hke-system",
            object_error_list: [],
            project: "star",
            entity_type: "paper",
            entity_id: 3689,
            function_type: "attempt",
            rule_set: "user",
            rule_type: "user_id",
            rule_value_1: "100001373",
            rule_value_2: "",
            rule_value_3: "",
            rule_value_4: "",
            status: "enabled",
            remarks: "",
          },
          {
            id: 7877,
            create_at: "2022-04-22 09:46:21",
            create_by: "hke-system",
            modify_at: "2022-04-22 09:46:21",
            modify_by: "hke-system",
            object_error_list: [],
            project: "star",
            entity_type: "paper",
            entity_id: 3689,
            function_type: "attempt",
            rule_set: "user",
            rule_type: "user_id",
            rule_value_1: "100001411",
            rule_value_2: "",
            rule_value_3: "",
            rule_value_4: "",
            status: "enabled",
            remarks: "",
          },
          {
            id: 7879,
            create_at: "2022-04-22 09:46:21",
            create_by: "hke-system",
            modify_at: "2022-04-22 09:46:21",
            modify_by: "hke-system",
            object_error_list: [],
            project: "star",
            entity_type: "paper",
            entity_id: 3689,
            function_type: "attempt",
            rule_set: "user",
            rule_type: "user_id",
            rule_value_1: "200000022",
            rule_value_2: "",
            rule_value_3: "",
            rule_value_4: "",
            status: "enabled",
            remarks: "",
          },
          {
            id: 7881,
            create_at: "2022-04-22 09:46:21",
            create_by: "hke-system",
            modify_at: "2022-04-22 09:46:21",
            modify_by: "hke-system",
            object_error_list: [],
            project: "star",
            entity_type: "paper",
            entity_id: 3689,
            function_type: "attempt",
            rule_set: "user",
            rule_type: "user_id",
            rule_value_1: "45278405",
            rule_value_2: "",
            rule_value_3: "",
            rule_value_4: "",
            status: "enabled",
            remarks: "",
          },
        ],
        status: {
          is_frozen: true,
          can_start: false,
          can_preview: true,
          can_view: true,
          can_modify: false,
          can_delete: false,
          can_assign: false,
          can_review: false,
          can_report: true,
          report_shared_num: 0,
          report_shared_accepted: true,
        },
      },
      Number.MAX_SAFE_INTEGER
    ),
  },
};
export const WithCommand: Story = {
  // render,
  args: {
    model: {
      ownerName: "John Doe",
      icon: "material-symbols:crossword",
      title: "lorem ipsum",
      description: "lorem ipsum",
      command: () => console.log("yyy"),
    },
  },
};
export const Mobile: Story = {
  // render,
  args: {
    model: {
      ownerName: "John Doe",
      icon: "material-symbols:crossword",
      title: "lorem ipsum",
      description: "lorem ipsum",
      command: () => console.log("yyy"),
    },
  },
  parameters: {
    viewport: {
      defaultViewport: "iphone14",
    },
  },
};
